import Head from "next/head";
import TodoList from "../components/TodoList";
import Image from "next/image";
import styles from "../styles/Home.module.css";

let todos = [
  {
    text: "Todoアプリを作る",
    id: "3d594650-3436-11e9-bc57-8b80ba54c431",
    isDone: false,
  },
  {
    text: "夕食を食べる",
    id: "3d599470-3436-11e9-bc57-8b80ba54c431",
    isDone: false,
  },
  {
    text: "朝食を食べる",
    id: "3d599471-3436-11e9-bc57-8b80ba54c431",
    isDone: true,
  },
  {
    text: "GraphQLとDBとの接続→https://apollographql-jp.com/tutorial/data-source/",
    id: "3d594650-3436-11e9-bc57-8b80ba54c431",
    isDone: false,
  },
  {
    text: "コンポーネントの分割考える",
    id: "3d599470-3436-11e9-bc57-8b80ba54c431",
    isDone: false,
  },
  {
    text: "スタイル調整する",
    id: "3d599471-3436-11e9-bc57-8b80ba54c431",
    isDone: false,
  },
];

const Home: React.FC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>Todo App</h1>
      </header>

      <main className={styles.main}>
        <h2>Todo一覧</h2>

        <form>
          <input type="text" name="todoname" placeholder="Todo Name" />
          <button type="submit">Add Todo</button>
        </form>

        <TodoList todos={todos} />
      </main>
    </div>
  );
};
export default Home;
