import React, { Suspense, useState } from "react";
import Head from "next/head";
import Header from "../components/Header";
import MainContainer from "../components/MainContainer";
import styles from "../common/styles/Home.module.css";

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Next.js Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className={styles.container}>
        <MainContainer />
      </div>
    </>
  );
};
export default Home;
